// gen-icons.mjs — generates icons-generated.js from @carbon/icons/es.
// Run automatically via `npm run build` (see package.json).
import { readdirSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';

const esDir = fileURLToPath(new URL('./node_modules/@carbon/icons/es', import.meta.url));
const outFile = fileURLToPath(new URL('./icons-generated.js', import.meta.url));
const sizes = [16, 20, 24, 32];

const iconDirs = readdirSync(esDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();

// Convert icon dir name to a valid JS identifier.
// e.g. "arrow--right" -> "_arrow__right", "4K" -> "_4K"
function toVarBase(name) {
    return '_' + name.replace(/--/g, '__').replace(/-/g, '_');
}

const importLines = [];
const registryEntries = [];

for (const iconName of iconDirs) {
    const base = toVarBase(iconName);
    const available = sizes.filter(s => existsSync(join(esDir, iconName, `${s}.js`)));
    if (available.length === 0) continue;

    for (const s of available) {
        importLines.push(`import ${base}_${s} from '@carbon/icons/es/${iconName}/${s}.js';`);
    }

    const sizeParts = available.map(s => `${s}: ${base}_${s}`).join(', ');
    // Use single or double-quoted key depending on whether the name needs quoting.
    const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(iconName) ? iconName : `'${iconName}'`;
    registryEntries.push(`    ${key}: { ${sizeParts} },`);
}

const output = [
    '// Code generated by gen-icons.mjs. DO NOT EDIT.',
    '',
    importLines.join('\n'),
    '',
    'export const goWasmBuildCarbonIcons = {',
    registryEntries.join('\n'),
    '};',
    '',
].join('\n');

writeFileSync(outFile, output);
console.log(`gen-icons: wrote ${iconDirs.length} icons to icons-generated.js`);
